### ISSUE TITLE
Azure CNI IP addresses exhausted, old pod IPs not being reclaimed?

### ISSUE THREAD

**Issue by rocketraman** [Azure/azure-container-networking#76] opened 2017-09-30 21:41 UTC
I have a Kubernetes 1.7.5 cluster which has run out of IPs to allocate, even though I only have about 15 pods running. Scheduling a new deployment fails. The events on the pod to be scheduled are:

```
default   2017-09-28 03:57:02 -0400 EDT   2017-09-28 03:57:02 -0400 EDT   1         hello-4059723819-8s35v   Pod       spec.containers{hello}   Normal    Pulled    kubelet, k8s-agentpool1-18117938-2   Successfully pulled image "myregistry.azurecr.io/mybiz/hello"
default   2017-09-28 03:57:02 -0400 EDT   2017-09-28 03:57:02 -0400 EDT   1         hello-4059723819-8s35v   Pod       spec.containers{hello}   Normal    Created   kubelet, k8s-agentpool1-18117938-2   Created container
default   2017-09-28 03:57:03 -0400 EDT   2017-09-28 03:57:03 -0400 EDT   1         hello-4059723819-8s35v   Pod       spec.containers{hello}   Normal    Started   kubelet, k8s-agentpool1-18117938-2   Started container
default   2017-09-28 03:57:13 -0400 EDT   2017-09-28 03:57:01 -0400 EDT   2         hello-4059723819-tj043   Pod                 Warning   FailedSync   kubelet, k8s-agentpool1-18117938-3   Error syncing pod
default   2017-09-28 03:57:13 -0400 EDT   2017-09-28 03:57:02 -0400 EDT   2         hello-4059723819-tj043   Pod                 Normal    SandboxChanged   kubelet, k8s-agentpool1-18117938-3   Pod sandbox changed, it will be killed and re-created.
default   2017-09-28 03:57:24 -0400 EDT   2017-09-28 03:57:01 -0400 EDT   3         hello-4059723819-tj043   Pod                 Warning   FailedSync   kubelet, k8s-agentpool1-18117938-3   Error syncing pod
default   2017-09-28 03:57:25 -0400 EDT   2017-09-28 03:57:02 -0400 EDT   3         hello-4059723819-tj043   Pod                 Normal    SandboxChanged   kubelet, k8s-agentpool1-18117938-3   Pod sandbox changed, it will be killed and re-created.
[...]
```

The dashboard looks like this:

![image](https://user-images.githubusercontent.com/53049/30989414-a1cad736-a46b-11e7-84f0-4a65ea066b3f.png)

Eventually, the dashboard shows the error:

```
Error: failed to start container "hello": Error response from daemon: {"message":"cannot join network of a non running container: 7e95918c6b546714ae20f12349efcc6b4b5b9c1e84b5505cf907807efd57525c"}
```

The kubelet log on the node shows that an IP address cannot be allocated due to "No available addresses":

    E0928 20:54:01.733682    1750 pod_workers.go:182] Error syncing pod 65127a94-a425-11e7-8d64-000d3af4357e ("hello-4059723819-xx16n_default(65127a94-a425-11e7-8d64-000d3af4357e)"), skipping: failed to "CreatePodSandbox" for "hello-4059723819-xx16n_default(65127a94-a425-11e7-8d64-000d3af4357e)" with CreatePodSandboxError: "CreatePodSandbox for pod \"hello-4059723819-xx16n_default(65127a94-a425-11e7-8d64-000d3af4357e)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"hello-4059723819-xx16n_default\" network: Failed to allocate address: Failed to delegate: Failed to allocate address: No available addresses"

I did have a cron job running on this cluster every minute, which would have created (and destroyed) a lot of pods in a short amount of time.

Is this perhaps a bug in Azure CNI not reclaiming IP addresses from terminated containers?

**How to reproduce it (as minimally and precisely as possible)**:

I believe this can be reproduced simply by starting and stopping many containers, such as by enabling the `batch/v2alpha1` API and running a CronJob every few seconds.

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**: Azure with Azure CNI networking plugin
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

- Kernel (e.g. `uname -a`): `Linux k8s-master-18117938-0 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: ACS-Engine
- Others:
Restarting the master has no effect

This is essentially a copy of upstream bug https://github.com/kubernetes/kubernetes/issues/53226.

**Comment by seanknox** [comment] 2017-09-30 22:13
Thanks for the reporting. Adding a few other Azure folks who are familiar with CNI: @lachie83 @anhowe

**Comment by sharmasushant** [comment] 2017-10-01 01:33
@rocketraman Thanks for letting us know! We will look into this.

**Comment by rocketraman** [comment] 2017-10-01 02:30
I'd also be interested in a workaround if you can provide one? Maybe some way to force cni to recycle unused IPs?

**Comment by jeffbarnes769** [comment] 2017-10-01 02:49
Not sure if increasing the default IP address pool using acs-engine helps
as a work around.  Realize CNI uses the azure-vnet command (please accept
my apologies if not - very much a newbie)

acs-engine will allocate 128 IP addresses on each node by default.
Depending on the size of your subnets, you can specify a custom value per
agent pool or the master profile by setting the ipAddressCount property in
agentPoolProfile and the masterProfile. The custom value must be in range
1-256.  from https://github.com/Azure/azure-container-networking/
blob/master/docs/acs.md


https://kubernetes.io/docs/concepts/cluster-administration/network-plugins/
https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md

**Comment by tamilmani1989** [comment] 2017-10-02 17:47
@rocketraman - Can you send us the CNI logs of node causing the issue?
Location of Logs:
/var/log/azure-vnet.log and /var/log/azure-vnet-ipam.log

**Comment by rocketraman** [comment] 2017-10-02 17:54
@tamilmani1989  On two of the five nodes in my cluster, I see DEL commands failing in the logs. On the other two nodes they have complete successfully. All five nodes were created at cluster creation time -- there is nothing special about the ones in which the DEL commands are failing. Here is a snippet of the failing DEL commands from those nodes.

```
2017/09/30 14:34:58 [cni-net] Plugin started.
2017/09/30 14:34:58 [cni-net] Processing DEL command with args {ContainerID:f363b81299c8676e0e5b491b05e31649d39ebb07b076864b7ace76064e2e300c Netns: IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=yyy-1506541740-fms3c;K8S_POD_INFRA_CONTAINER_ID=f363b81299c8676e0e5b491b05e31649d39ebb07b076864b7ace76064e2e300c Path:/opt/azure-vnet/bin:/opt/cni/bin}.
2017/09/30 14:34:58 [cni-net] Read network configuration &{CNIVersion:0.2.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:}}.
2017/09/30 14:34:58 [net] Deleting endpoint f363b812-eth0 from network azure.
2017/09/30 14:34:58 [net] Deleting veth pair azvethf363b81 eth0.
2017/09/30 14:34:58 [net] Failed to delete veth pair azvethf363b81: route ip+net: no such network interface.
2017/09/30 14:34:58 [net] Failed to delete endpoint f363b812-eth0, err:route ip+net: no such network interface.
2017/09/30 14:34:58 [azure-vnet] Failed to delete endpoint: route ip+net: no such network interface.
2017/09/30 14:34:58 [cni-net] DEL command completed with err:Failed to delete endpoint: route ip+net: no such network interface.
2017/09/30 14:34:58 [cni-net] Plugin stopped.
2017/09/30 14:35:58 [cni-net] Plugin azure-vnet version v0.9.
2017/09/30 14:35:58 [cni-net] Running on Linux version 4.4.0-96-generic (buildd@lgw01-10) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
2017/09/30 14:35:58 [net] Network interface: {Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback} with IP addresses: [127.0.0.1/8 ::1/128]
2017/09/30 14:35:58 [net] Network interface: {Index:2 MTU:1500 Name:eth0 HardwareAddr:00:0d:3a:f4:4c:84 Flags:up|broadcast} with IP addresses: [fe80::20d:3aff:fef4:4c84/64]
2017/09/30 14:35:58 [net] Network interface: {Index:3 MTU:1500 Name:docker0 HardwareAddr:02:42:dc:35:55:9f Flags:up|broadcast|multicast} with IP addresses: [172.17.0.1/16 fe80::42:dcff:fe35:559f/64]
2017/09/30 14:35:58 [net] Network interface: {Index:6 MTU:1500 Name:azure0 HardwareAddr:00:0d:3a:f4:4c:84 Flags:up|broadcast|multicast} with IP addresses: [10.2.0.189/17 fe80::20d:3aff:fef4:4c84/64]
2017/09/30 14:35:58 [net] Network interface: {Index:19 MTU:1500 Name:azveth28b1e3f HardwareAddr:2e:21:ca:a4:c9:f0 Flags:up|broadcast} with IP addresses: [fe80::2c21:caff:fea4:c9f0/64]
2017/09/30 14:35:58 [net] Network interface: {Index:21 MTU:1500 Name:azveth311e7b3 HardwareAddr:7e:6f:ae:1b:57:fc Flags:up|broadcast} with IP addresses: [fe80::7c6f:aeff:fe1b:57fc/64]
2017/09/30 14:35:58 [net] Network interface: {Index:33 MTU:1500 Name:azveth0a6ad70 HardwareAddr:ca:eb:65:0e:88:b7 Flags:up|broadcast} with IP addresses: [fe80::c8eb:65ff:fe0e:88b7/64]
2017/09/30 14:35:58 [net] Network interface: {Index:997 MTU:1500 Name:azvethafa8f14 HardwareAddr:ba:83:b7:bb:27:f8 Flags:up|broadcast} with IP addresses: [fe80::b883:b7ff:febb:27f8/64]
2017/09/30 14:35:58 [net] Network interface: {Index:1005 MTU:1500 Name:azvethab20fbc HardwareAddr:16:2f:c3:44:5b:ff Flags:up|broadcast} with IP addresses: [fe80::142f:c3ff:fe44:5bff/64]
2017/09/30 14:35:58 [net] Store timestamp is 2017-09-28 07:57:01.325437193 +0000 UTC.
2017/09/30 14:35:58 [net] Restored state, &{Version:v0.9 TimeStamp:2017-09-28 07:57:01.329397489 +0000 UTC ExternalInterfaces:map[eth0:0xc420138000] store:0xc420016de0 Mutex:{state:0 sema:0}}
```

And here are the logs from the other failing node:

```
017/09/24 16:16:56 [cni-net] Plugin started.
2017/09/24 16:16:56 [cni-net] Processing DEL command with args {ContainerID:c62015c61b57966292b1890cce11063f4ae84e8693275060df75269af6044f15 Netns: IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=xxx-1760939698-f7sv9;K8S_POD_INFRA_CONTAINER_ID=c62015c61b57966292b1890cce11063f4ae84e8693275060df75269af6044f15 Path:/opt/azure-vnet/bin:/opt/cni/bin}.
2017/09/24 16:16:56 [cni-net] Read network configuration &{CNIVersion:0.2.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:}}.
2017/09/24 16:16:56 [net] Deleting endpoint c62015c6-eth0 from network azure.
2017/09/24 16:16:56 [net] Deleting veth pair azvethc62015c eth0.
2017/09/24 16:16:56 [net] Failed to delete veth pair azvethc62015c: route ip+net: no such network interface.
2017/09/24 16:16:56 [net] Failed to delete endpoint c62015c6-eth0, err:route ip+net: no such network interface.
2017/09/24 16:16:56 [azure-vnet] Failed to delete endpoint: route ip+net: no such network interface.
2017/09/24 16:16:56 [cni-net] DEL command completed with err:Failed to delete endpoint: route ip+net: no such network interface.
2017/09/24 16:16:56 [cni-net] Plugin stopped.
2017/09/24 16:17:56 [cni-net] Plugin azure-vnet version v0.9.
2017/09/24 16:17:56 [cni-net] Running on Linux version 4.4.0-96-generic (buildd@lgw01-10) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
2017/09/24 16:17:56 [net] Network interface: {Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback} with IP addresses: [127.0.0.1/8 ::1/128]
2017/09/24 16:17:56 [net] Network interface: {Index:2 MTU:1500 Name:eth0 HardwareAddr:00:0d:3a:f4:40:d8 Flags:up|broadcast} with IP addresses: [fe80::20d:3aff:fef4:40d8/64]
2017/09/24 16:17:56 [net] Network interface: {Index:3 MTU:1500 Name:docker0 HardwareAddr:02:42:b5:1e:06:b2 Flags:up|broadcast|multicast} with IP addresses: [172.17.0.1/16 fe80::42:b5ff:fe1e:6b2/64]
2017/09/24 16:17:56 [net] Network interface: {Index:6 MTU:1500 Name:azure0 HardwareAddr:00:0d:3a:f4:40:d8 Flags:up|broadcast|multicast} with IP addresses: [10.2.0.34/17 fe80::20d:3aff:fef4:40d8/64]
2017/09/24 16:17:56 [net] Network interface: {Index:7 MTU:1500 Name:azvethf0707dd HardwareAddr:96:4d:44:62:41:41 Flags:up|broadcast} with IP addresses: [fe80::944d:44ff:fe62:4141/64]
2017/09/24 16:17:56 [net] Network interface: {Index:9 MTU:1500 Name:azveth2756177 HardwareAddr:d6:9d:87:8c:fb:10 Flags:up|broadcast} with IP addresses: [fe80::d49d:87ff:fe8c:fb10/64]
2017/09/24 16:17:56 [net] Network interface: {Index:11 MTU:1500 Name:azveth38821cd HardwareAddr:9e:43:20:62:15:51 Flags:up|broadcast} with IP addresses: [fe80::9c43:20ff:fe62:1551/64]
2017/09/24 16:17:56 [net] Network interface: {Index:33 MTU:1500 Name:azvetheb8b62e HardwareAddr:52:70:e3:04:55:d3 Flags:up|broadcast} with IP addresses: [fe80::5070:e3ff:fe04:55d3/64]
2017/09/24 16:17:56 [net] Network interface: {Index:35 MTU:1500 Name:azveth4a96cc1 HardwareAddr:c6:20:f6:59:89:ea Flags:up|broadcast} with IP addresses: [fe80::c420:f6ff:fe59:89ea/64]
2017/09/24 16:17:56 [net] Network interface: {Index:41 MTU:1500 Name:azvethbed0aa2 HardwareAddr:da:00:d2:e5:ed:1a Flags:up|broadcast} with IP addresses: [fe80::d800:d2ff:fee5:ed1a/64]
2017/09/24 16:17:56 [net] Store timestamp is 2017-09-23 18:21:22.550734741 +0000 UTC.
2017/09/24 16:17:56 [net] Restored state, &{Version:v0.9 TimeStamp:2017-09-23 18:21:22.553208047 +0000 UTC ExternalInterfaces:map[eth0:0xc4200180c0] store:0xc420066d80 Mutex:{state:0 sema:0}}
```

Every single DEL command on these two nodes is failing in the same way.

For contrast, here are some logs for the DEL command on one of the three **working** nodes.

```
2017/09/21 03:48:12 [cni-net] Plugin started.
2017/09/21 03:48:12 [cni-net] Processing DEL command with args {ContainerID:d7462e28528cb029b3c77732913ed044185284c47748872ab635dee5f3050243 Netns:/proc/2093/ns/net IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system
;K8S_POD_NAME=heapster-2888171832-vdhg1;K8S_POD_INFRA_CONTAINER_ID=d7462e28528cb029b3c77732913ed044185284c47748872ab635dee5f3050243 Path:/opt/azure-vnet/bin:/opt/cni/bin}.
2017/09/21 03:48:12 [cni-net] Read network configuration &{CNIVersion:0.2.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:}}.
2017/09/21 03:48:12 [net] Deleting endpoint d7462e28-eth0 from network azure.
2017/09/21 03:48:12 [net] Deleting veth pair azvethd7462e2 eth0.
2017/09/21 03:48:13 [net] Deleting ARP reply rule for IP address 10.2.0.133/17 on d7462e28-eth0.
2017/09/21 03:48:13 [net] Deleting MAC DNAT rule for IP address 10.2.0.133/17 on d7462e28-eth0.
2017/09/21 03:48:13 [net] Deleted endpoint &{Id:d7462e28-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azvethd7462e2 MacAddress:0e:35:4a:88:b0:d0 IPAddresses:[{IP:10.2.0.133 Mask:ffff8000}] Gateways:[10.2.0.1]}.
2017/09/21 03:48:13 [net] Save succeeded.
2017/09/21 03:48:13 [cni] Calling plugin azure-vnet-ipam DEL nwCfg:&{CNIVersion:0.2.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:10.2.0.0/17 Address:10.2.0.133 QueryInterval:}}.
2017/09/21 03:48:13 [cni] Plugin azure-vnet-ipam returned err:<nil>.
2017/09/21 03:48:13 [cni-net] DEL command completed with err:<nil>.
2017/09/21 03:48:13 [cni-net] Plugin stopped.
2017/09/21 03:48:13 [cni-net] Plugin azure-vnet version v0.9.
2017/09/21 03:48:13 [cni-net] Running on Linux version 4.4.0-96-generic (buildd@lgw01-10) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
2017/09/21 03:48:13 [net] Network interface: {Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback} with IP addresses: [127.0.0.1/8 ::1/128]
2017/09/21 03:48:13 [net] Network interface: {Index:2 MTU:1500 Name:eth0 HardwareAddr:00:0d:3a:f4:44:42 Flags:up|broadcast} with IP addresses: [fe80::20d:3aff:fef4:4442/64]
2017/09/21 03:48:13 [net] Network interface: {Index:3 MTU:1500 Name:docker0 HardwareAddr:02:42:d3:09:07:e4 Flags:up|broadcast|multicast} with IP addresses: [172.17.0.1/16 fe80::42:d3ff:fe09:7e4/64]
2017/09/21 03:48:13 [net] Network interface: {Index:6 MTU:1500 Name:azure0 HardwareAddr:00:0d:3a:f4:44:42 Flags:up|broadcast|multicast} with IP addresses: [10.2.0.127/17 fe80::20d:3aff:fef4:4442/64]
2017/09/21 03:48:13 [net] Store timestamp is 2017-09-21 03:48:13.004817097 +0000 UTC.
2017/09/21 03:48:13 [net] Restored state, &{Version:v0.9 TimeStamp:2017-09-21 03:48:13.0061967 +0000 UTC ExternalInterfaces:map[eth0:0xc420018600] store:0xc420016de0 Mutex:{state:0 sema:0}}
```

Let me know if this is sufficient? If you provide some contact info, I can send more complete logs  privately.

**Comment by tamilmani1989** [comment] 2017-10-02 18:24
@rocketraman - Can you please attach both azure-vnet and azure-vnet-ipam logs of any one of failing nodes by dragging and dropping?

**Comment by rocketraman** [comment] 2017-10-02 19:08
@tamilmani1989 Ok 
[azure-vnet-logs.zip](https://github.com/Azure/azure-container-networking/files/1350032/azure-vnet-logs.zip)

**Comment by tamilmani1989** [comment] 2017-10-02 20:17
@rocketraman Have you manually deleted any of the veth interfaces(eg: azvethf363b81) in node?

**Comment by sharmasushant** [comment] 2017-10-02 20:50
@rocketraman Are you using acs-engine? Is it possible that delete is getting called before create is finished? Can you tell a little bit more about how you are orchestrating creation and deletion of containers? We will need logs that contain both creation and deletion of containers. Your previous logs does not seem to have creation.

**Comment by rocketraman** [comment] 2017-10-02 22:29
@tamilmani1989 No I have not deleted any interfaces manually. I *did* delete one vnet IP address from the portal a couple of days ago, as I was trying to find a way to recover from this. I quickly restored it, realizing that approach wasn't going to get me anywhere. However, any logs from September should not be affected by this at all.

@sharmasushant I uploaded all of the logs in the zip file above. Yes, I am using acs-engine.

**Comment by sharmasushant** [comment] 2017-10-03 18:28
We looked further. It seems that container namespace and veth is being removed prior to the call being made to CNI for deleting endpoint. As per CNI spec, we need to handle this and release IPs even if veth/container-namespace are missing.  We will provide a bug fix for this. Thanks @rocketraman for reporting this.

**Comment by rocketraman** [comment] 2017-10-03 20:58
@sharmasushant Great!

Now that you have found the issue, are you able to provide a workaround?

**Comment by rocketraman** [comment] 2017-10-10 05:41
Any news on the fix for this serious issue?

**Comment by sharmasushant** [comment] 2017-10-10 21:14
@rocketraman Sorry for the delay. Some internal deliverables required our attention so this got delayed. We are targeting next week for a new release that will have fix for the issue. Will keep you posted.

**Comment by rocketraman** [comment] 2017-10-16 14:38
@sharmasushant Following up on this, thanks!

**Comment by rocketraman** [comment] 2017-10-22 15:19
@tamilmani1989 @sharmasushant I see you guys merged e246fec3cb460a10223aa3234a4fce6088e5b348 that fixes this... awesome! A reference to this issue number somewhere in the commit log would have been nice to confirm this is fixed. Assuming that it is, when do you this will be released and included in acs-engine?

**Comment by rocketraman** [comment] 2017-10-24 20:36
@sharmasushant I believe acs-engine is downloading the CNI plugin from https://acs-mirror.azureedge.net/cni/cni-plugins-amd64-latest.tgz. Can you make updating that URL a part of the release process for CNI?

cc: @colemickens

**Comment by sharmasushant** [comment] 2017-10-24 21:43
Sure @rocketraman, We will make the process of updating acs-engine more streamlined.

**Comment by edevil** [comment] 2017-11-29 15:06
This issue is open, but the comments seem to indicate this has been fixed.

Whats the current state?

**Comment by sharmasushant** [comment] 2017-12-05 17:48
@edevil Yes, the issue is now fixed.

**Comment by edevil** [comment] 2017-12-05 18:02
Closing the issue would make it clear.

**Comment by sharmasushant** [comment] 2017-12-05 18:52
This is now fixed. Closing the issue.

**Closed by sharmasushant** 2017-12-05 18:52 UTC
