### ISSUE TITLE
[Egress] npm dropping output traffic

### ISSUE THREAD

**Issue by ferantivero** [Azure/azure-container-networking#528] opened 2020-03-17 02:21 UTC
**Is this a request for help?**: YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**Which release version?**: v1.0.32

---

**Which component (CNI/IPAM/CNM/CNS)**: NPM

---

**Which Operating System (Linux/Windows)**: Linux
---

**For Linux: Include Distro and kernel version using "uname -a"**: Linux aks-agentpool-37083126-vmss000000 4.15.0-1069-azure #74-Ubuntu SMP Fri Feb 7 17:22:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**: Kubernetes 1.15.5

---

**What happened**:

## Setup

```
+--------------------+        +--------------------+
|     AKS Cluster    |        |   Azure Firewall   |
|       Subnet       |        |       Subnet       |
|     (np rules)     |        |     (fw rules)     |
+--------------------+        +--------------------+
                     |        |
                     |        |
                     +--+RT+--+
```

> Important: please note Azure Firewall rules are created before Network Policies rules. 

## Before Network Policies configuration

> Important: at this point, any pod is being able to establish a connection with Azure resources that are allowed by the Azure Firewall

#### IpTables before creating the Network Policies

```bash
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-EXTERNAL-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes externally-visible service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain KUBE-EXTERNAL-SERVICES (1 references)
target     prot opt source               destination

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  10.10.0.0/21         anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             10.10.0.0/21         /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-SERVICES (3 references)
target     prot opt source               destination
```

### Result before applying Network Policies (expected 👍)

```
# wget -S https://****.vault.azure.net                                 
Connecting to ****.vault.azure.net (52.168.109.101:443)
wget: note: TLS certificate validation not implemented
...

# iptstate
Source                      Destination                Prt State       TTL
10.10.0.19:52085            10.2.0.10:53               udp               0:00:04
10.10.0.19:35314            52.168.109.101:443         tcp ESTABLISHED  23:59:34
10.10.0.19:45732            10.2.0.10:53               udp               0:00:04
```

### DROP ALL
I'm trying following the practice DROP-all-first (a.k.a deny all)

```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: dev-deny-all
  namespace: backend-dev
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

#### IpTables after applying deny all Network Policy
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-EXTERNAL-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes externally-visible service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
AZURE-NPM  all  --  anywhere             anywhere
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain AZURE-NPM (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
AZURE-NPM-INGRESS-PORT  all  --  anywhere             anywhere
AZURE-NPM-EGRESS-PORT  all  --  anywhere             anywhere
AZURE-NPM-TARGET-SETS  all  --  anywhere             anywhere

Chain AZURE-NPM-EGRESS-PORT (1 references)
target     prot opt source               destination

Chain AZURE-NPM-EGRESS-TO (0 references)
target     prot opt source               destination

Chain AZURE-NPM-INGRESS-FROM (0 references)
target     prot opt source               destination

Chain AZURE-NPM-INGRESS-PORT (1 references)
target     prot opt source               destination

Chain AZURE-NPM-TARGET-SETS (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             match-set azure-npm-2662673593 src /* DROP-ALL-FROM-ns-backend-dev */
DROP       all  --  anywhere             anywhere             match-set azure-npm-2662673593 dst /* DROP-ALL-TO-ns-backend-dev */

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain KUBE-EXTERNAL-SERVICES (1 references)
target     prot opt source               destination

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  10.10.0.0/21         anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             10.10.0.0/21         /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-SERVICES (3 references)
target     prot opt source               destination
```

### Result after deny all (expected 👍)
```
# wget -S https://****.vault.azure.net                                 
wget: bad address '****.vault.azure.net'
...

# iptstate
Filters: src: 10.10.0.19
Source                      Destination                Prt State       TTL
<e m p t y>
```

### Core DNS
Then, ACCEPT OUTPUT for UPD 53. This way we don't get a bad address result.

```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: dns-dev
  namespace: backend-dev
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

#### IpTables after allowing DNS resolution
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-EXTERNAL-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes externally-visible service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
AZURE-NPM  all  --  anywhere             anywhere
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain AZURE-NPM (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
AZURE-NPM-INGRESS-PORT  all  --  anywhere             anywhere
AZURE-NPM-EGRESS-PORT  all  --  anywhere             anywhere
AZURE-NPM-TARGET-SETS  all  --  anywhere             anywhere

Chain AZURE-NPM-EGRESS-PORT (1 references)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             match-set azure-npm-530439631 dst udp dpt:domain match-set azure-npm-2662673593 src /* ALLOW-all-namespaces-AND-UDP-PORT-53-FROM-ns-backend-dev */
AZURE-NPM-TARGET-SETS  all  --  anywhere             anywhere             match-set azure-npm-2662673593 src /* ALLOW-ALL-FROM-ns-backend-dev-TO-JUMP-TO-AZURE-NPM-TARGET-SETS */

Chain AZURE-NPM-EGRESS-TO (0 references)
target     prot opt source               destination

Chain AZURE-NPM-INGRESS-FROM (0 references)
target     prot opt source               destination

Chain AZURE-NPM-INGRESS-PORT (1 references)
target     prot opt source               destination

Chain AZURE-NPM-TARGET-SETS (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             match-set azure-npm-2662673593 src /* DROP-ALL-FROM-ns-backend-dev */
DROP       all  --  anywhere             anywhere             match-set azure-npm-2662673593 dst /* DROP-ALL-TO-ns-backend-dev */

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain KUBE-EXTERNAL-SERVICES (1 references)
target     prot opt source               destination

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  10.10.0.0/21         anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             10.10.0.0/21         /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-SERVICES (3 references)
target     prot opt source               destination
```

#### Result after allowing egress for DNS (not expected 👎)

and yet, my pods can't output traffic to external resources. I mean, I don't get a bad address but connections can't be established (it results in timeout).

```
# wget -S https://****.vault.azure.net
Connecting to ****.vault.azure.net (52.168.109.101:443)
wget: can't connect to remote host (52.168.109.101): Connection timed out
...

# iptstate
Filters: src: 10.10.0.19
Source                      Destination                Prt State       TTL
10.10.0.19:60845            10.2.0.10:53               udp               0:00:24
10.10.0.19:45526            10.2.0.10:53               udp               0:00:24
```

> Important: note the missing established connection against 52.168.109.101:443

---

**What you expected to happen**:

based on the premise [Network Policies should be for east-west traffic, while NSG/FW deals with north-south traffic](https://docs.microsoft.com/en-us/azure/virtual-network/kubernetes-network-policies#planning-security-for-your-kubernetes-cluster), I would've expected my pods can establish a connection with any external resources allowed by the Azure Firewall without Network Policies interference. 

That being said, after applying the deny-all it is ok to drop all connections between `pods`, but I would've expected to be able to open connections against Azure resources that are blessed in my Azure Firewall.

---

**How to reproduce it** (as minimally and precisely as possible):

1. create an AKS cluster
2. limit egress using Azure Firewall
3. apply all above Network Policies in order 
4. within any pod in the backend-dev namespace, try to resolve using `wget` to any internet facing resource
---

**Anything else we need to know**:

I could workaround it by creating an egress rule (allow all or a specific one) that takes care of external traffic. But ideally, I'd prefer not to duplicate rules in Azure Firewall and Network Policies.

Also, I'm almost sure I had tested it with v1.0.27 before and it was working properly. But I could be wrong.

---

**Comment by jaer-tsun** [comment] 2020-03-17 18:09
Hi @ferantivero, are you trying to allow all egress traffic from backend-dev via udp 53? In your example you're only allowing traffic to all-namespaces via udp 53, which does not include external traffic.

Here's an example that allows all egress via udp 53 from backend-dev

```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: dns-dev
  namespace: backend-dev
spec:
  egress:
  - to:
    ports:
    - port: 53
      protocol: UDP
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

**Comment by ferantivero** [comment] 2020-03-17 20:04
@jaer-tsun please let me give try on this.

**Comment by ferantivero** [comment] 2020-03-17 22:52
@jaer-tsun, In short, it didn't work (Short and Full updates below). But please take your time, no hurries at all :)

Please let me answer your question here: _are you trying to allow all egress traffic from backend-dev via udp 53?_
>  Not just that, I've done that already, and it is working properly based on my understanding. What I do-not-want is Network Policies to interfere with north-south traffic even after deny-all network policy is created, as I expect Network Policies to only take care of Pod-To-Pod connections, it means within the AKS Cluster subnet.  

But please let me remark why I conceptually expect such thing, from "What you expected to happen" section, please let me re-share what is the original intent: 
> based on the premise [Network Policies should be for east-west traffic, while NSG/FW deals with north-south traffic](https://docs.microsoft.com/en-us/azure/virtual-network/kubernetes-network-policies#planning-security-for-your-kubernetes-cluster), I would've expected my pods can establish a connection with any external resources allowed by the Azure Firewall without Network Policies interference.

> That being said, after applying the deny-all it is ok to drop all connections between pods, but I would've expected to be able to open connections against Azure resources that are blessed in my Azure Firewall (e.g Azure KeyVault).

## Short update

please find a screenshot below on how the proposal change has impacted at IpTable level

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/158487/76907831-fc3cbf00-6885-11ea-9950-c5dd575d6b2e.png">

and yet, my pods can't reach external Azure resources (e.g. Azure KeyVault). 

## Full update
1. just tested the proposal and I didn't work 
2. still no external access, my pods are still facing `Connection timed out` trying to reach Azure KeyVault
3. Please let me share how the object looks like in k8s after creation, IpTables, and result after applying the proposed Network Policy

### Core DNS (take 2 using proposal change)

this is the new _allow all egress via udp 53 from backend-dev_ expecting being able to ACCEPT OUTPUT for UPD 53. This way, we don't get a bad address result. But also, we are able to reach external services (internet facing) that are allowed by our Azure Firewall.

```yaml
# kubectl get networkpolicy dns-dev -n backend-dev -o yaml

apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"dns-dev","namespace":"backend-dev"},"spec":{"egress":[{"ports":[{"port":53,"protocol":"UDP"}],"to":null}],"podSelector":{},"policyTypes":["Ingress","Egress"]}}
  creationTimestamp: "2020-03-17T21:43:34Z"
  name: dns-dev
  namespace: backend-dev
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

#### IpTables after allowing DNS resolution (take 2)

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-EXTERNAL-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes externally-visible service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
AZURE-NPM  all  --  anywhere             anywhere
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain AZURE-NPM (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
AZURE-NPM-INGRESS-PORT  all  --  anywhere             anywhere
AZURE-NPM-EGRESS-PORT  all  --  anywhere             anywhere
AZURE-NPM-TARGET-SETS  all  --  anywhere             anywhere

Chain AZURE-NPM-EGRESS-PORT (1 references)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain match-set azure-npm-2662673593 src /* ALLOW-ALL-TO-UDP-PORT-53-FROM-ns-backend-dev */
AZURE-NPM-TARGET-SETS  all  --  anywhere             anywhere             match-set azure-npm-2662673593 src /* ALLOW-ALL-FROM-ns-backend-dev-TO-JUMP-TO-AZURE-NPM-TARGET-SETS */

Chain AZURE-NPM-EGRESS-TO (0 references)
target     prot opt source               destination

Chain AZURE-NPM-INGRESS-FROM (0 references)
target     prot opt source               destination

Chain AZURE-NPM-INGRESS-PORT (1 references)
target     prot opt source               destination

Chain AZURE-NPM-TARGET-SETS (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             match-set azure-npm-2662673593 src /* DROP-ALL-FROM-ns-backend-dev */
DROP       all  --  anywhere             anywhere             match-set azure-npm-2662673593 dst /* DROP-ALL-TO-ns-backend-dev */

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain KUBE-EXTERNAL-SERVICES (1 references)
target     prot opt source               destination

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  10.10.0.0/21         anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             10.10.0.0/21         /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-SERVICES (3 references)
target     prot opt source               destination
```

#### Result after applying the proposed Network Policy for Dns  (not expected 👎)

```
# wget -S https://*****.vault.azure.net
Connecting to *****.vault.azure.net (52.168.109.101:443)
wget: can't connect to remote host (52.168.109.101): Connection timed out

# iptstate
Source                      Destination                Prt State       TTL
10.10.0.19:53762            10.2.0.10:53               udp               0:00:19
10.10.0.19:49801            10.2.0.10:53               udp               0:00:19
```

> Important: please note it still missing the established connection against 52.168.109.101:443

**Comment by jaer-tsun** [comment] 2020-03-17 23:31
Wouldn't you have to allow egress to tcp 443? not sure if I'm misunderstanding something here...

**Comment by jaer-tsun** [comment] 2020-03-17 23:43
I'm still not completely sure what you're trying to do, but...

If you want external traffic you'll need to add a rule for it
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: dns-dev
  namespace: backend-dev
spec:
  egress:
  - to:
    ports:
    - port: 53
      protocol: UDP
  - to: []
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

Can you tell me what you're trying to restrict/allow?

**Comment by ferantivero** [comment] 2020-03-18 00:42
thanks for sharing that @jaer-tsun, the thing is I see that as a workaround. Please take a look at the section above: “Anything else we need to know” 

Regarding, 

> Can you tell me what you're trying to restrict/allow?

Egress
 restrict: all 
 allow: udp 53 only 

### Expected

After applying such restrictive Network Policy rules, I can still reach for instance Azure KeyVault (external Azure resource).
The reason I expect this is because it is south traffic and I want that to be managed exclusively by Azure Firewall and do-not-duplicate my firewall rules at l Network Policy level: https://docs.microsoft.com/en-us/azure/virtual-network/kubernetes-network-policies#planning-security-for-your-kubernetes-cluster

### Actual

I can not access Azure KeyVault even allowing that in the Azure Firewall.

What am I missing here, I mean conceptually speaking?

**Comment by jaer-tsun** [comment] 2020-03-18 01:10
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: dns-dev
  namespace: backend-dev
spec:
  egress:
  - to:
    ports:
    - port: 53
      protocol: UDP
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```
The above policy only allows egress via UDP 53 so that should satisfy
> Egress
restrict: all
allow: udp 53 only

When you make a call to azkv, it's correctly dropping the traffic.

If you want the external traffic to be dropped by az firewall instead of NPM, you may need to configure [ipblock](https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors) to allow that external traffic and block the rest.

**Comment by ferantivero** [comment] 2020-03-18 14:04
first of all @jaer-tsun thanks for your support 💪

When you say, 

> When you make a call to azkv, it's correctly dropping the traffic.

Based on my understanding this [doc](https://docs.microsoft.com/en-us/azure/virtual-network/kubernetes-network-policies#planning-security-for-your-kubernetes-cluster) is recommending us to plan the exact opposite. Even more  “if” it is correct to drop external traffic (south), we‘d need to duplicate egress rules at Azure Firewall and Network Policy level.

Regarding, 

> If you want the external traffic to be dropped by az firewall instead of NPM, you may need to configure ipblock to allow that external traffic and block the rest.

I really do-not-want, please note Network Policy does not manage concepts like Azure Service Tags to deal with Public Ip changes and it just layer 4 (ipblock).

Please note in our solution we have multiple resources like:
1. azkv 
2. appinsights
3. azcosmosdb 
4. azredis

It is not practical to maintain these rules in both, Azure Firewall and Network Policies and at the same time we would like to prevent the solution from `allowAll` workaround:

```yaml
egress:
- to: []
```

I’m sure I’m missing something here.

**Comment by jaer-tsun** [comment] 2020-03-18 16:51
I can see that the doc is making it black and white but:

- with ipblock you'd be allowing 0.0.0.0/0 and blocking e.g. {pod subnet}
- with other ingress policies you can block traffic from backend-dev or a label in backend-dev for pods that have external access

[According to k8s](https://kubernetes.io/docs/concepts/services-networking/network-policies/#isolated-and-non-isolated-pods), pods become isolated once network policies are applied on them.

Also, here are some egress examples regarding my response.
- under section [Subnets and IP Addresses (IPBlocks)](https://medium.com/@reuvenharrison/an-introduction-to-kubernetes-network-policies-for-security-people-ba92dd4c809d)
- in [this example](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/14-deny-external-egress-traffic.md), external is blocked since it's not specified

**Comment by ferantivero** [comment] 2020-03-18 18:21
again thanks for your support @jaer-tsun, and thanks for sharing the resources, I'm pretty much familiarized with them all :)

We would've expected another sort of integration among AKS-NPM-AzFW/NS, and still confused why NPM is blocking north-south, I mean more than just Pod-To-Pod communications. 

Additionally, I think it was working differently in v1.0.27. But I might be wrong. 

Please feel free to close this issue as by design, unless you consider otherwise.

**Comment by jaer-tsun** [comment] 2020-03-18 18:37
NPM controls ingress/egress to/from pods and that isn't limited by in cluster or external traffic. 

Unfortunately, v1.0.27 introduced a lot of bugs and since then, we've addressed them according to k8s specs to achieve parity with Calico NPM. Also, there weren't any integration with AzFW/NSG taken into account during the design.

thanks @ferantivero for understanding and feel free to contact us for any issues in the future

*closing this issue as npm is working as designed

**Closed by jaer-tsun** 2020-03-18 18:37 UTC
