### ISSUE TITLE
NetworkPlugin cni failed to set up pod issues

### ISSUE THREAD

**Issue by jjeyaraj** [Azure/azure-container-networking#339] opened 2019-04-18 00:20 UTC
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
Version: v0.34.1
GitCommit: e68d84850
GitTreeState: clean
---

**Kubernetes version**:
1.14.1

**What happened**:
we are constantly having issues with our windows pods going down and not being able to restart.

When deployed the pods are healthy and running, eventually, the degrade and get into a state where they can't restart.

This is the log spew we get:
`6c7-5sgp9": NetworkPlugin cni failed to set up pod "rpsapi-5d8fcd96c7-5sgp9_default" network: unexpected end of JSON input

  Warning  FailedCreatePodSandBox  17m                   kubelet, 3247k8s010  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "71b7cd958f20857e9913005fb348f03e0011af75a92ddf6a2532caadc10ad872" network for pod "rpsapi-5d8fcd96c7-5sgp9": NetworkPlugin cni failed to set up pod "rpsapi-5d8fcd96c7-5sgp9_default" network: unexpected end of JSON input

  Normal   SandboxChanged          2m59s (x11 over 53m)  kubelet, 3247k8s010  Pod sandbox changed, it will be killed and re-created.

  Warning  FailedCreatePodSandBox  111s (x3 over 9m21s)  kubelet, 3247k8s010  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "057b64a49300540ba680a9f7f789bc4a0f6e96564e90e5fe84b828f0870332a8" network for pod "rpsapi-5d8fcd96c7-5sgp9": NetworkPlugin cni failed to set up pod "rpsapi-5d8fcd96c7-5sgp9_default" network: unexpected end of JSON input`

**What you expected to happen**:
Pods are expected to be healthy and running.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the windows pods to be serviced by a ngnix for requests.
Eventually, after few hours the pods fail and unable to restart.

**Anything else we need to know**:
This is the config we are using:
{
"apiVersion": "vlabs",
"properties": {
"orchestratorProfile": {
"orchestratorType": "Kubernetes",
"orchestratorVersion": "1.14.1"
},
"masterProfile": {
"count": 1,
"dnsPrefix": "mrprpsapi16",
"vmSize": "Standard_D2_v3"
},
"agentPoolProfiles": [
{
"name": "linuxpool3",
"count": 2,
"vmSize": "Standard_D2_v2",
"availabilityProfile": "AvailabilitySet"
},
{
"name": "windowspool4",
"count": 10,
"vmSize": "Standard_D2s_v3",
"availabilityProfile": "AvailabilitySet",
"osType": "Windows",
"extensions": [
{
"name": "winrm"
}
]
}
],
"extensionProfiles": [
{
"name": "winrm",
"version": "v1"
}
],
"windowsProfile": {
"adminUsername": "xxxxxxxxxxxxxxxxxxxxxx",
"adminPassword": "xxxxxxxxxxxxxxxxxxxxxxxxx"
},
"linuxProfile": {
"adminUsername": "azureuser",
"ssh": {
"publicKeys": [
{
"keyData": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
]
}
},
"servicePrincipalProfile": {
"clientId": "xxxxxxxxxxxxxxxxx",
"secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
}
}

**Comment by zhiweiv** [comment] 2019-04-18 02:52
#306 reproduced again today /w AKS-Engine 0.34.0 & Azure CNI 1.0.18, as described before,
in C:\K azure-vnet-ipam.json is 3KB with only whitespace in it, azure-vnet.json is missing, there is a lock file azure-vnet.json.lock.

```
04/18/2019  01:05 AM             3,593 azure-vnet-ipam.json
04/18/2019  01:27 AM           751,943 azure-vnet-ipam.log
04/18/2019  01:15 AM         2,501,781 azure-vnet-telemetry.log
04/18/2019  01:27 AM                 4 azure-vnet.json.lock
04/18/2019  02:44 AM         3,814,758 azure-vnet.log
04/18/2019  01:16 AM         5,244,352 azure-vnet.log.1
04/13/2019  05:07 AM               803 azure.json
```

I can see this in azure-vnet.log
```
2019/04/18 02:49:32 Formatted Boot time: 2019-04-18 01:14:13
2019/04/18 02:49:32 [cni] reboot time 2019-04-18 01:14:13 +0000 UTC storeLockFile mod time 2019-04-18 01:27:52.4105429 +0000 UTC
2019/04/18 02:49:53 [cni] Failed to lock store: timed out locking store.
2019/04/18 02:49:53 Failed to initialize key-value store of network plugin, err:timed out locking store.
2019/04/18 02:49:53 Report plugin error
2019/04/18 02:49:53 [Azure-Utils] ver
2019/04/18 02:49:53 Formatted Boot time: 2019-04-18 01:14:13
2019/04/18 02:49:53 [cni] reboot time 2019-04-18 01:14:13 +0000 UTC storeLockFile mod time 2019-04-18 01:27:52.4105429 +0000 UTC
2019/04/18 02:50:15 [cni] Failed to lock store: timed out locking store.
2019/04/18 02:50:15 Failed to initialize key-value store of network plugin, err:timed out locking store.
2019/04/18 02:50:15 Report plugin error
2019/04/18 02:50:15 [Azure-Utils] ver
2019/04/18 02:50:17 Formatted Boot time: 2019-04-18 01:14:13
2019/04/18 02:50:17 [cni] reboot time 2019-04-18 01:14:13 +0000 UTC storeLockFile mod time 2019-04-18 01:27:52.4105429 +0000 UTC
2019/04/18 02:50:39 [cni] Failed to lock store: timed out locking store.
2019/04/18 02:50:39 Failed to initialize key-value store of network plugin, err:timed out locking store.
2019/04/18 02:50:39 Report plugin error
2019/04/18 02:50:39 [Azure-Utils] ver
2019/04/18 02:50:39 Formatted Boot time: 2019-04-18 01:14:13
2019/04/18 02:50:39 [cni] reboot time 2019-04-18 01:14:13 +0000 UTC storeLockFile mod time 2019-04-18 01:27:52.4105429 +0000 UTC
2019/04/18 02:51:00 [cni] Failed to lock store: timed out locking store.
2019/04/18 02:51:00 Failed to initialize key-value store of network plugin, err:timed out locking store.
2019/04/18 02:51:00 Report plugin error
2019/04/18 02:51:00 [Azure-Utils] ver
2019/04/18 02:51:02 Formatted Boot time: 2019-04-18 01:14:13
2019/04/18 02:51:02 [cni] reboot time 2019-04-18 01:14:13 +0000 UTC storeLockFile mod time 2019-04-18 01:27:52.4105429 +0000 UTC
2019/04/18 02:51:24 [cni] Failed to lock store: timed out locking store.
2019/04/18 02:51:24 Failed to initialize key-value store of network plugin, err:timed out locking store.
2019/04/18 02:51:24 Report plugin error
2019/04/18 02:51:24 [Azure-Utils] ver
2019/04/18 02:51:24 Formatted Boot time: 2019-04-18 01:14:13
2019/04/18 02:51:24 [cni] reboot time 2019-04-18 01:14:13 +0000 UTC storeLockFile mod time 2019-04-18 01:27:52.4105429 +0000 UTC
2019/04/18 02:51:45 [cni] Failed to lock store: timed out lock
```

**Comment by zhiweiv** [comment] 2019-04-18 03:13
@jjeyaraj 
You can try this workaround to repair Windows nodes.

ssh to Windows node

Stop-Service Kubelet -Force
<del azure-vnet.json file, if exist>
<del azure-vnet.json.lock, if exist>
<del azure-vnet-ipam.json file, if exist>
<del azure-vnet-ipam.json.lock file, if exist>
Start-Service kubelet

**Comment by jjeyaraj** [comment] 2019-04-20 00:38
I am using the latest version v1.0.20 and still dealing with issue.

The pods are having the "6c7-5sgp9": NetworkPlugin cni failed to set up pod "rpsapi-5d8fcd96c7-5sgp9_default" network: unexpected end of JSON input" error and nodes are flipping due to:
PLEG not ready

Our live traffic is being affected by this with end users experiencing outages, is there a fix for this?

**Comment by KnicKnic** [comment] 2019-05-31 17:34
I also experienced this probelm with aks engine and kubernetes 1.13

**Comment by ashvindeodhar** [comment] 2019-06-04 20:37
@KnicKnic, @jjeyaraj Can you please include C:\K\azure-vnet.log and C:\K\azure-vnet-ipam.log when this issue is seen?

**Comment by ashvindeodhar** [comment] 2019-06-06 19:26
This is a known HNS issue and have been fixed as a part of https://support.microsoft.com/en-us/help/4497934/windows-10-update-kb4497934 .  Can you please upgrade your machine with this update?

**Comment by ashvindeodhar** [comment] 2019-06-12 20:27
@KnicKnic / @jjeyaraj  were you able to upgrade with the patch ?

**Comment by KnicKnic** [comment] 2019-06-13 05:33
I switched to wincni, it solved my problem, thanks.

**Comment by draiche** [comment] 2019-06-28 18:59
We were seeing the same issues, and then applied the June cumulative update (KB4503327) and it went away for a couple of weeks.. but suddenly we're seeing a huge amount of the same failures on several of our worker nodes again.

```
2019/06/28 18:42:30 [Azure-Utils] ver
2019/06/28 18:42:32 Formatted Boot time: 2019-06-21 20:34:55
2019/06/28 18:42:32 [cni] reboot time 2019-06-21 20:34:55 +0000 UTC storeLockFile mod time 2019-06-27 08:08:01.9013691 +0000 UTC
2019/06/28 18:42:36 [cni] Failed to lock store: timed out locking store.
2019/06/28 18:42:36 Failed to initialize key-value store of network plugin, err:timed out locking store.
```

```
2019/06/28 18:44:24 [Azure-Utils] ver
E0628 18:44:29.620127    3480 remote_runtime.go:109] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to set up sandbox container "63d4db212e4d670cbe1c1774ce6dc46efd712af2f3d19042f9ead2d0ff2907fc" network for pod "<podname>": NetworkPlugin cni failed to set up pod "<podname>main-development" network: unexpected end of JSON input
E0628 18:44:29.620127    3480 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "<podname>main-development(74becc34-99d3-11e9-bfa0-000d3a1e58e4)" failed: rpc error: code = Unknown desc = failed to set up sandbox container "63d4db212e4d670cbe1c1774ce6dc46efd712af2f3d19042f9ead2d0ff2907fc" network for pod "<podname>": NetworkPlugin cni failed to set up pod "<podname>main-development" network: unexpected end of JSON input
E0628 18:44:29.620127    3480 kuberuntime_manager.go:693] createPodSandbox for pod "<podname>_main-development(74becc34-99d3-11e9-bfa0-000d3a1e58e4)" failed: rpc error: code = Unknown desc = failed to set up sandbox container "63d4db212e4d670cbe1c1774ce6dc46efd712af2f3d19042f9ead2d0ff2907fc" network for pod "<podname>": NetworkPlugin cni failed to set up pod "<podname>main-development" network: unexpected end of JSON input
E0628 18:44:29.620127    3480 pod_workers.go:190] Error syncing pod 74becc34-99d3-11e9-bfa0-000d3a1e58e4 ("<podname>main-development(74becc34-99d3-11e9-bfa0-000d3a1e58e4)"), skipping: failed to "CreatePodSandbox" for "<podname>_main-development(74becc34-99d3-11e9-bfa0-000d3a1e58e4)" with CreatePodSandboxError: "CreatePodSandbox for pod \"<podname>_main-development(74becc34-99d3-11e9-bfa0-000d3a1e58e4)\" failed: rpc error: code = Unknown desc = failed to set up sandbox container \"63d4db212e4d670cbe1c1774ce6dc46efd712af2f3d19042f9ead2d0ff2907fc\" network for pod \"<podname>\": NetworkPlugin cni failed to set up pod \"<podname>main-development\" network: unexpected end of JSON input"
E0628 18:44:30.082906    3480 file.go:104] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
2019/06/28 18:44:30 Formatted Boot time: 2019-06-21 20:34:55
2019/06/28 18:44:30 Connected to telemetry service
```

```
PS C:\Users\azureuser> get-hotfix

Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
2714k8s000... Update           KB4495590                          5/19/2019 12:00:00 AM
2714k8s000... Update           KB4494174                          5/19/2019 12:00:00 AM
2714k8s000... Security Update  KB4499728                          5/19/2019 12:00:00 AM
2714k8s000... Security Update  KB4504369     NT AUTHORITY\SYSTEM  6/12/2019 12:00:00 AM
2714k8s000... Security Update  KB4503327     NT AUTHORITY\SYSTEM  6/12/2019 12:00:00 AM
```

**Comment by ashvindeodhar** [comment] 2019-07-25 21:46
@draiche what's the cni version? can you attach c:\k folder contents as zip?

**Comment by ngrigoriev** [comment] 2019-09-03 20:01
I think I have captured the issue. Still do not know how to reproduce it, but I may have the logs. 

At some point the plug-in enters a particular state and never recovers until restarted (node reboot in my case):

```
2019/09/02 13:11:15 [Azure-Utils] ver
2019/09/02 13:11:16 Formatted Boot time: 2019-08-22 19:48:23
2019/09/02 13:11:16 [cni] reboot time 2019-08-22 19:48:23 +0000 UTC storeLockFile mod time 2019-09-02 13:07:48.0585624 +0000 UTC
2019/09/02 13:11:29 [cni] Failed to lock store: timed out locking store.
2019/09/02 13:11:29 Failed to initialize key-value store of network plugin, err:timed out locking store.
2019/09/02 13:11:29 Report plugin error
```

This seems to be preceded by a number of messaged referring to "degraded object":

```
2019/09/02 13:07:48 handleConsecutiveAdd failed with error There was an operation attempted on a degraded object.
2019/09/02 13:07:48 [cni-net] ADD command completed with result:Interfaces:[{Name:eth0 Mac: Sandbox:}], DNS:{Nameservers:[] Domain: Search:[] Options:[]} err:<nil>.
2019/09/02 13:07:48 Failed to execute network plugin, err:There was an operation attempted on a degraded object..
2019/09/02 13:07:48 [cni-net] Plugin stopped.
```

**Comment by matmerr** [comment] 2020-06-25 22:17
Closing due to staleness, if the issue persists, please reopen.

**Closed by matmerr** 2020-06-25 22:17 UTC
